### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by figo-fe** [ijse/freemarker.js#6]
我写了一个最简单的例子，打印html，返回undefined，如果打印err，则 errno: 34,code:'ENOENT'，代码如下：

'use strict';

var Freemarker = require('freemarker.js');
var fm = new Freemarker({
  viewRoot: '/template',
  options: {
    /*\* for fmpp */
  }
});

fm.render('test.ftl',{},function(err,html,output){
    console.log(html)// undefined
});

**Comment by figo-fe** [comment]
另外发现 fmpOpts.outputRoot 这个好像没有用到

**Comment by ijse** [comment]
需要配置好依赖的环境：jdk
