### ISSUE TITLE
发现一些问题

### ISSUE THREAD

**Issue by figo-fe** [ijse/freemarker.js#7]
1、lib/fmpp.js 中为什么有两个 run function
2、为什么 需要写入到tmpfile 然后再去读取，不能直接使用fmpp合成的html代码么
3、此插件貌似会有权限问题，Temp文件夹下无写权限

**Comment by ijse** [comment]
1. 当时做的时候，fmpp好像没办法直接输出到stdout中
2. 这个其实是个工具库，是由`os.getTmpDir()`命令获取系统临时文件夹目录后操作的，所以权限问题请检查下你的系统环境或使用步骤。
