### ISSUE TITLE
关于Date,Datetime类型数据如何伪造

### ISSUE THREAD

**Issue by figo-fe** [ijse/freemarker.js#8]
之前在ftl中创建时间类型mockdata时 可以这样 <#assign time = '2015-06-25'?datetime('yyyy-MM-dd')>，但是使用json文件存储伪造数据，如何创建时间类型的数据？

**Comment by ijse** [comment]
你可以在fmpp options中添加自己定义的DateFormat, 参照fmpp文档：http://fmpp.sourceforge.net/configfile.html

freemarker.js的处理过程见这段代码：https://github.com/ijse/freemarker.js/blob/master/index.js#L59-L73
