### ISSUE TITLE
发现一个bug，请修复

### ISSUE THREAD

**Issue by figo-fe** [ijse/freemarker.js#9]
运行时会提示 Can't find lcp.bat! 
修复方案：fmpp官网下载fmpp包，在bin目录把lcp.bat 放到 你的项目里 跟 fmpp.bat同级即可。
希望可以尽快修复 不然我每次使用的时候npm install 之后还得自己去拷这个文件。

**Comment by ijse** [comment]
应该不需要吧，你的环境是怎样的？

**Comment by figo-fe** [comment]
环境是只装了java jdk，其他没装。
而且我发现你其实已经把fmpp放到包里面了 所以也不需要装fmpp，但是fmpp需要用到lcp.bat，你的包里没有。我不清楚这个东西是做什么的，但是没有的话就会报错。

**Comment by ijse** [comment]
哦，了解了。你用的是Windows， 所以才需要那个文件。

**Comment by ijse** [comment]
@figo-fe  已经更新：https://github.com/ijse/freemarker.js/commit/f3dcd17a854e3bc2f65a4139fc6f7ad8a32ecd55
